server:
  port: 8081
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.134:8848
        group: group-1
        namespace: ba312bc4-9357-4e06-9f3a-480e628f8d0c
      config:
        file-extension: yaml
        server-addr: 192.168.1.134:8848

#    config:
#      discovery:
#        enabled: true
#        service-id: gateway-server
#      uri: http://localhost:8082
    gateway:
      routes:
        - id: service                      # 路由id
          uri: http://localhost:8083/      # 路由指向的服务地址
          predicates:
          - Weight=group1,5                # 设置分组和权重，按照路由权重选择同一个分组中的路由
          - Path=/service/**               # 匹配以service开头的请求
          filters:
          - StripPrefix=2                  # 去掉path中的第一个节点
        - id: user
          uri: http://localhost:8084/
          predicates:
          - Weight=group1,5
          - Path=/user/**
          filters:
          - StripPrefix=1
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8082/eureka/
